server:
  port: 8081

spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:mysql://52.79.33.61:3307/jamjam?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: jamjam
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, email, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: profile_nickname, profile_image
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

app:
  jwt:
    secret: ${JWT_SECRET:change-me-please-32bytes-minimum-xxxxxxxxxxxxxxxx}
    expiration-ms: 2592000000  # 30일
  oauth2:
    # 로그인 성공 후 FE로 리다이렉트할 URL(토큰 전달)
    redirect-uri: ${OAUTH2_REDIRECT_URI:http://localhost:3000/oauth2/success}
  kakao:
    local-api-key: ${KAKAO_LOCAL_API_KEY}   # dapi.kakao.com (좌표->행정구역)
logging:
  level:
    org.springframework.security: INFO
